### PR TITLE
vimc-6273: add gavi74 column to country_metadata

### PR DESCRIPTION
**Pull request by xiangli313**
Youtrack:
https://mrc-ide.myjetbrains.com/youtrack/issue/VIMC-6273

Hi @kgaythorpe and @r-ash, here is a migration script adding column `gavi74` to table `country_metadata`.

### CODE REVIEW

**Review by r-ash — COMMENTED** [review]
The other columns gavi72, gavi77 etc. have a not null constraint - is there a reason we don't have that here?

**Comment by xiangli313** [comment]
We need to allow it null-able, populate it, then set not null.

**Comment by r-ash** [comment]
If we set all TRUE or all FALSE as part of this migration and add the not null constraint we can avoid running 2 migrations. Should reduce the wait time a bit as means we only have to redeploy once

**Comment by xiangli313** [comment]
Oh, nice. I like that idea.

**Review by r-ash — APPROVED** [review]

**Pull request merged**
